repos:
  - repo: https://github.com/cpp-linter/cpp-linter-hooks
    rev: v0.5.0  # Use the ref you want to point at
    hooks:
      - id: clang-format
        args: [--style=Google --dry-run] # Other coding style: LLVM, GNU, Chromium, Microsoft, Mozilla, WebKit.
      - id: clang-tidy
        args: [--checks='boost-*,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-*']
  - repo: https://github.com/pre-commit-pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
